// Generated by scripts/build-web.mjs — offline cache for Zuzanky deník.
const CACHE = "zd-msoh2j8i";
const ASSETS = [
 "./",
 "./_expo/static/js/web/entry-886dc77e12b0a75524b6cd3e9eecb0e8.js",
 "./apple-touch-icon.png",
 "./assets/node_modules/@expo-google-fonts/baloo-2/400Regular/Baloo2_400Regular.20f6d0043a8ab7fd4a6466f6f6611685.ttf",
 "./assets/node_modules/@expo-google-fonts/baloo-2/500Medium/Baloo2_500Medium.cf867a5944fb838010f772a139620a75.ttf",
 "./assets/node_modules/@expo-google-fonts/baloo-2/600SemiBold/Baloo2_600SemiBold.61e1563819bc0ab5fc68673fc4909c99.ttf",
 "./assets/node_modules/@expo-google-fonts/baloo-2/700Bold/Baloo2_700Bold.f57ab981c1dec25a04bea3cce20ea18c.ttf",
 "./assets/node_modules/@expo-google-fonts/baloo-2/800ExtraBold/Baloo2_800ExtraBold.15e8199eb1b3d423d8642f1837b3a9c4.ttf",
 "./assets/node_modules/@expo-google-fonts/quicksand/300Light/Quicksand_300Light.271e0c24a39dadbe933bc774f64f68f5.ttf",
 "./assets/node_modules/@expo-google-fonts/quicksand/400Regular/Quicksand_400Regular.5845af22f839a90a9cca3b8ec0e3cff4.ttf",
 "./assets/node_modules/@expo-google-fonts/quicksand/500Medium/Quicksand_500Medium.95906e2457ee777801b3ca4b02b4947c.ttf",
 "./assets/node_modules/@expo-google-fonts/quicksand/600SemiBold/Quicksand_600SemiBold.dc8fa3ed1fa18875d0aac23ecbf64e02.ttf",
 "./assets/node_modules/@expo-google-fonts/quicksand/700Bold/Quicksand_700Bold.8003228962d5cafb549cf4034f9ece07.ttf",
 "./assets/node_modules/expo-router/assets/arrow_down.017bc6ba3fc25503e5eb5e53826d48a8.png",
 "./assets/node_modules/expo-router/assets/error.d1ea1496f9057eb392d5bbf3732a61b7.png",
 "./assets/node_modules/expo-router/assets/file.19eeb73b9593a38f8e9f418337fc7d10.png",
 "./assets/node_modules/expo-router/assets/forward.d8b800c443b8972542883e0b9de2bdc6.png",
 "./assets/node_modules/expo-router/assets/pkg.ab19f4cbc543357183a20571f68380a3.png",
 "./assets/node_modules/expo-router/assets/react-navigation/elements/back-icon-mask.0a328cd9c1afd0afe8e3b1ec5165b1b4.png",
 "./assets/node_modules/expo-router/assets/react-navigation/elements/back-icon.35ba0eaec5a4f5ed12ca16fabeae451d.png",
 "./assets/node_modules/expo-router/assets/react-navigation/elements/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55.png",
 "./assets/node_modules/expo-router/assets/react-navigation/elements/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55@2x.png",
 "./assets/node_modules/expo-router/assets/react-navigation/elements/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55@3x.png",
 "./assets/node_modules/expo-router/assets/react-navigation/elements/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55@4x.png",
 "./assets/node_modules/expo-router/assets/react-navigation/elements/close-icon.808e1b1b9b53114ec2838071a7e6daa7.png",
 "./assets/node_modules/expo-router/assets/react-navigation/elements/close-icon.808e1b1b9b53114ec2838071a7e6daa7@2x.png",
 "./assets/node_modules/expo-router/assets/react-navigation/elements/close-icon.808e1b1b9b53114ec2838071a7e6daa7@3x.png",
 "./assets/node_modules/expo-router/assets/react-navigation/elements/close-icon.808e1b1b9b53114ec2838071a7e6daa7@4x.png",
 "./assets/node_modules/expo-router/assets/react-navigation/elements/search-icon.286d67d3f74808a60a78d3ebf1a5fb57.png",
 "./assets/node_modules/expo-router/assets/sitemap.412dd9275b6b48ad28f5e3d81bb1f626.png",
 "./assets/node_modules/expo-router/assets/unmatched.20e71bdf79e3a97bf55fd9e164041578.png",
 "./favicon.ico",
 "./icon-192.png",
 "./icon-512.png",
 "./index.html",
 "./manifest.webmanifest",
 "./metadata.json"
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  if (req.mode === 'navigate') {
    // Network-first for the app shell: online opens always get the newest
    // version; the cached copy only serves when offline.
    event.respondWith(
      fetch('./index.html')
        .then((res) => {
          const clone = res.clone();
          caches.open(CACHE).then((c) => c.put('./index.html', clone));
          return res;
        })
        .catch(() => caches.match('./index.html'))
    );
    return;
  }
  event.respondWith(
    caches.match(req).then(
      (cached) =>
        cached ||
        fetch(req).then((res) => {
          if (res.ok && new URL(req.url).origin === self.location.origin) {
            const clone = res.clone();
            caches.open(CACHE).then((c) => c.put(req, clone));
          }
          return res;
        })
    )
  );
});
